version: '3'
services:
  codecept:
    image: codeception/codeception
    depends_on:
      - chrome
    volumes:
      - .:/project
  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "5900:5900"