version: '3'
services:
  codecept:
    image: codeception/codeception
    depends_on:
      - firefox
    volumes:
      - .:/project
  firefox:
    image: selenium/standalone-firefox-debug
    ports:
      - "5900:5900"